version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    actions-deps:
      patterns:
        - "*"
# Go mod bot configurations
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
# Docker bot configurations
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    docker-deps:
      patterns:
        - "*"
